
/*
 * Filename: tsk_cyclic.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_CYCLIC
#define _H_DEFINE_TSK_CYCLIC

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_CYCLIC_INCLUDES */

/* USER CODE END TSK_CYCLIC_INCLUDES */



/*
* description: Cyclic task for cyclic runnables
* events: 
* mode: Cyclic
* name: tsk_cyclic
* shortname: cyclic
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: 0
* timertickperiod: 10
*/
DeclareTask(tsk_cyclic);


#endif