
/*
 * Filename: tsk_event.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_TSK_EVENT
#define _H_DEFINE_TSK_EVENT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_EVENT_INCLUDES */

/* USER CODE END TSK_EVENT_INCLUDES */



/*
* description: Task for event triggered runnables
* events: ev_event_onData
* mode: Event
* name: tsk_event
* shortname: event
* signalpoolsRO: sp_common
* signalpoolsRW: sp_common
* tickEvent: 0
* timertickperiod: 0
*/
DeclareTask(tsk_event);


#endif