
/*
 * Filename: sc_clock_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#ifndef _H_DEFINE_SC_CLOCK_TYPE
#define _H_DEFINE_SC_CLOCK_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_CLOCK_INCLUDES */
#include "statemachine.h"
#include "swc_clock.h"
/* USER CODE END SC_CLOCK_INCLUDES */

/**********************************************************************
 *       Type Definition for SC_CLOCK signal    
 **********************************************************************/

/* USER CODE START SC_CLOCK_USERDEFINITIONS */
    
typedef enum {
    CLOCK_HOURSWIDGET,
    CLOCK_MINUTESWIDGET
}CLOCK_active_widget_t;

typedef struct {
    CLOCK_state_t                           m_widgetState;
    STATE_stateOuterTransitionTable_t*      m_transitions;
    uint8_t                                 m_value;
    
}CLOCK_widget_t;

/* USER CODE END SC_CLOCK_USERDEFINITIONS */

typedef 
/* USER CODE START SC_CLOCK_SIGNALDATADEFINITION */
struct
{
    CLOCK_state_t                           m_containerState;
    STATE_stateOuterTransitionTable_t*      m_transitions;
    CLOCK_active_widget_t                   m_activeWidget;
    CLOCK_widget_t                          m_hours;
    CLOCK_widget_t                          m_minutes;
} 
/* USER CODE END SC_CLOCK_SIGNALDATADEFINITION */
SC_CLOCK_data_t;

/* USER CODE START InitSC_CLOCK */
#define SC_CLOCK_INIT_DATA ((SC_CLOCK_data_t){STATE_CLOCK_C_ISDISPLAYING, 0, CLOCK_HOURSWIDGET, {STATE_CLOCK_W_ISDISPLAYING, 0, 0}, {STATE_CLOCK_W_ISDISPLAYING, 0, 0}})
/* USER CODE END InitSC_CLOCK */


/* USER CODE START SC_CLOCK_USERFUNCTIONS */

/* USER CODE END SC_CLOCK_USERFUNCTIONS */


#endif