

/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_event.h"
#include "sc_event_type.h"
#include "sc_clock.h"
#include "sc_clock_type.h"
#include "sc_display.h"
#include "sc_display_type.h"



/* signal configuration */
/*
* description: Events to trigger various tasks and runnables
* indriver: 0
* name: so_event
* onDataError: 0
* onDataUpdate: ev_event_onData
* outdriver: 0
* resource: None
* shortname: event
* signalclass: sc_event
* signalpool: sp_common
*/


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_event_updTasks = { tsk_event };
 

static const SC_EVENT_cfg_t SO_EVENT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_event_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_event_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_event */


/* signal data */

SC_EVENT_t SO_EVENT_signal= 
{
   /* init value    */  SC_EVENT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_EVENT_cfg,
}; /* data so_event */

/* signal configuration */
/*
* description: Clock signal content
* indriver: 0
* name: so_clock
* onDataError: 0
* onDataUpdate: 0
* outdriver: 0
* resource: None
* shortname: clock
* signalclass: sc_clock
* signalpool: sp_common
*/

 

static const SC_CLOCK_cfg_t SO_CLOCK_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_clock */


/* signal data */

SC_CLOCK_t SO_CLOCK_signal= 
{
   /* init value    */  SC_CLOCK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_CLOCK_cfg,
}; /* data so_clock */

/* signal configuration */
/*
* description: Clock display object
* indriver: 0
* name: so_display
* onDataError: 0
* onDataUpdate: 0
* outdriver: default
* resource: None
* shortname: display
* signalclass: sc_display
* signalpool: sp_common
*/

 

static const SC_DISPLAY_cfg_t SO_DISPLAY_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_DISPLAY_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  NULL,
   
}; /* configuration so_display */


/* signal data */

SC_DISPLAY_t SO_DISPLAY_signal= 
{
   /* init value    */  SC_DISPLAY_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_DISPLAY_cfg,
}; /* data so_display */



void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_EVENT_incAge( &SO_EVENT_signal, tick); 
   RTE_SC_CLOCK_incAge( &SO_CLOCK_signal, tick); 
   RTE_SC_DISPLAY_incAge( &SO_DISPLAY_signal, tick); 
   
}


